rates:
  robot_state: 20.0
  metrics: 0.04
  lease: 1.0
  front_image: 10.0
  side_image: 10.0
  rear_image: 10.0
auto_claim: True
auto_power_on: True
auto_stand: True

mode_parent_odom_tf: odom # odom or vision
publish_odom: false
use_enu_frame: true
